// megafunction wizard: %FIFO%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: dcfifo_mixed_widths 

// ============================================================
// File Name: exp_3x3_ker_fifo_8.v
// Megafunction Name(s):
// 			dcfifo_mixed_widths
//
// Simulation Library Files(s):
// 			
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 17.1.0 Build 590 10/25/2017 SJ Standard Edition
// ************************************************************


//Copyright (C) 2017  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details.


//dcfifo_mixed_widths DEVICE_FAMILY="Cyclone V" LPM_NUMWORDS=16 LPM_SHOWAHEAD="OFF" LPM_WIDTH=64 LPM_WIDTH_R=8 LPM_WIDTHU=4 LPM_WIDTHU_R=7 OVERFLOW_CHECKING="ON" RDSYNC_DELAYPIPE=3 READ_ACLR_SYNCH="OFF" UNDERFLOW_CHECKING="ON" USE_EAB="ON" WRITE_ACLR_SYNCH="OFF" WRSYNC_DELAYPIPE=3 aclr data q rdclk rdempty rdreq wrclk wrreq wrusedw INTENDED_DEVICE_FAMILY="Cyclone V" ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 17.1 cbx_a_gray2bin 2017:10:19:05:46:40:SJ cbx_a_graycounter 2017:10:19:05:46:40:SJ cbx_altdpram 2017:10:19:05:46:40:SJ cbx_altera_counter 2017:10:19:05:46:40:SJ cbx_altera_gray_counter 2017:10:19:05:46:40:SJ cbx_altera_syncram 2017:10:19:05:46:40:SJ cbx_altera_syncram_nd_impl 2017:10:19:05:46:40:SJ cbx_altsyncram 2017:10:19:05:46:40:SJ cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_dcfifo 2017:10:19:05:46:40:SJ cbx_fifo_common 2017:10:19:05:46:40:SJ cbx_lpm_add_sub 2017:10:19:05:46:40:SJ cbx_lpm_compare 2017:10:19:05:46:40:SJ cbx_lpm_counter 2017:10:19:05:46:40:SJ cbx_lpm_decode 2017:10:19:05:46:40:SJ cbx_lpm_mux 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_nadder 2017:10:19:05:46:40:SJ cbx_scfifo 2017:10:19:05:46:40:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ cbx_stratixiii 2017:10:19:05:46:40:SJ cbx_stratixv 2017:10:19:05:46:40:SJ cbx_util_mgl 2017:10:19:05:46:40:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//a_gray2bin device_family="Cyclone V" WIDTH=5 bin gray
//VERSION_BEGIN 17.1 cbx_a_gray2bin 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  exp_3x3_ker_fifo_8_a_gray2bin
	( 
	bin,
	gray) /* synthesis synthesis_clearbox=1 */;
	output   [4:0]  bin;
	input   [4:0]  gray;

	wire  xor0;
	wire  xor1;
	wire  xor2;
	wire  xor3;

	assign
		bin = {gray[4], xor3, xor2, xor1, xor0},
		xor0 = (gray[0] ^ xor1),
		xor1 = (gray[1] ^ xor2),
		xor2 = (gray[2] ^ xor3),
		xor3 = (gray[4] ^ gray[3]);
endmodule //exp_3x3_ker_fifo_8_a_gray2bin


//a_graycounter DEVICE_FAMILY="Cyclone V" PVALUE=0 WIDTH=5 aclr clock cnt_en q
//VERSION_BEGIN 17.1 cbx_a_gray2bin 2017:10:19:05:46:40:SJ cbx_a_graycounter 2017:10:19:05:46:40:SJ cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ  VERSION_END

//synthesis_resources = reg 6 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  exp_3x3_ker_fifo_8_a_graycounter
	( 
	aclr,
	clock,
	cnt_en,
	q) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clock;
	input   cnt_en;
	output   [4:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[4:0]	counter4a;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	parity3;
	wire  [4:0]  cntr_cout;
	wire  parity_cout;
	wire sclr;
	wire updown;

	// synopsys translate_off
	initial
		counter4a[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter4a[0:0] <= 1'b0;
		else
			if (sclr == 1'b1) counter4a[0:0] <= 1'b0;
			else  counter4a[0:0] <= ((cnt_en & (counter4a[0:0] ^ (~ parity_cout))) | ((~ cnt_en) & counter4a[0:0]));
	// synopsys translate_off
	initial
		counter4a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter4a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) counter4a[1:1] <= 1'b0;
			else  counter4a[1:1] <= (counter4a[1:1] ^ (counter4a[0:0] & cntr_cout[0]));
	// synopsys translate_off
	initial
		counter4a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter4a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) counter4a[2:2] <= 1'b0;
			else  counter4a[2:2] <= (counter4a[2:2] ^ (counter4a[1:1] & cntr_cout[1]));
	// synopsys translate_off
	initial
		counter4a[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter4a[3:3] <= 1'b0;
		else
			if (sclr == 1'b1) counter4a[3:3] <= 1'b0;
			else  counter4a[3:3] <= (counter4a[3:3] ^ (counter4a[2:2] & cntr_cout[2]));
	// synopsys translate_off
	initial
		counter4a[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter4a[4:4] <= 1'b0;
		else
			if (sclr == 1'b1) counter4a[4:4] <= 1'b0;
			else  counter4a[4:4] <= (counter4a[4:4] ^ cntr_cout[3]);
	// synopsys translate_off
	initial
		parity3 = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) parity3 <= {1{1'b1}};
		else
			if (sclr == 1'b1) parity3 <= 1'b0;
			else  parity3 <= ((cnt_en & ((((counter4a[0] ^ counter4a[1]) ^ counter4a[2]) ^ counter4a[3]) ^ counter4a[4])) | ((~ cnt_en) & parity3));
	assign
		cntr_cout = {1'b0, (cntr_cout[2] & (~ counter4a[2:2])), (cntr_cout[1] & (~ counter4a[1:1])), (cntr_cout[0] & (~ counter4a[0:0])), (cnt_en & parity_cout)},
		parity_cout = (((~ parity3) ^ (~ updown)) & cnt_en),
		q = counter4a,
		sclr = 1'b0,
		updown = 1'b1;
endmodule //exp_3x3_ker_fifo_8_a_graycounter


//a_graycounter DEVICE_FAMILY="Cyclone V" PVALUE=1 WIDTH=5 aclr clock cnt_en q ALTERA_INTERNAL_OPTIONS=suppress_da_rule_internal=S102
//VERSION_BEGIN 17.1 cbx_a_gray2bin 2017:10:19:05:46:40:SJ cbx_a_graycounter 2017:10:19:05:46:40:SJ cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ  VERSION_END

//synthesis_resources = reg 6 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"suppress_da_rule_internal=S102;{-to counter5a[0]} POWER_UP_LEVEL=HIGH"} *)
module  exp_3x3_ker_fifo_8_a_graycounter1
	( 
	aclr,
	clock,
	cnt_en,
	q) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   clock;
	input   cnt_en;
	output   [4:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[4:0]	counter5a;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=LOW"} *)
	reg	parity6;
	wire  [4:0]  cntr_cout;
	wire  parity_cout;
	wire sclr;
	wire updown;

	// synopsys translate_off
	initial
		counter5a[0:0] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[0:0] <= {1{1'b1}};
		else
			if (sclr == 1'b1) counter5a[0:0] <= 1'b0;
			else  counter5a[0:0] <= ((cnt_en & (counter5a[0:0] ^ (~ parity_cout))) | ((~ cnt_en) & counter5a[0:0]));
	// synopsys translate_off
	initial
		counter5a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[1:1] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[1:1] <= 1'b0;
			else  counter5a[1:1] <= (counter5a[1:1] ^ (counter5a[0:0] & cntr_cout[0]));
	// synopsys translate_off
	initial
		counter5a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[2:2] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[2:2] <= 1'b0;
			else  counter5a[2:2] <= (counter5a[2:2] ^ (counter5a[1:1] & cntr_cout[1]));
	// synopsys translate_off
	initial
		counter5a[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[3:3] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[3:3] <= 1'b0;
			else  counter5a[3:3] <= (counter5a[3:3] ^ (counter5a[2:2] & cntr_cout[2]));
	// synopsys translate_off
	initial
		counter5a[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) counter5a[4:4] <= 1'b0;
		else
			if (sclr == 1'b1) counter5a[4:4] <= 1'b0;
			else  counter5a[4:4] <= (counter5a[4:4] ^ cntr_cout[3]);
	// synopsys translate_off
	initial
		parity6 = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr)
		if (aclr == 1'b1) parity6 <= 1'b0;
		else
			if (sclr == 1'b1) parity6 <= 1'b0;
			else  parity6 <= ((cnt_en & ((((counter5a[0] ^ counter5a[1]) ^ counter5a[2]) ^ counter5a[3]) ^ counter5a[4])) | ((~ cnt_en) & parity6));
	assign
		cntr_cout = {1'b0, (cntr_cout[2] & (~ counter5a[2:2])), (cntr_cout[1] & (~ counter5a[1:1])), (cntr_cout[0] & (~ counter5a[0:0])), (cnt_en & parity_cout)},
		parity_cout = ((parity6 ^ updown) & cnt_en),
		q = counter5a,
		sclr = 1'b0,
		updown = 1'b1;
endmodule //exp_3x3_ker_fifo_8_a_graycounter1


//altsyncram ADDRESS_ACLR_B="CLEAR1" ADDRESS_REG_B="CLOCK1" CLOCK_ENABLE_INPUT_B="BYPASS" DEVICE_FAMILY="Cyclone V" OPERATION_MODE="DUAL_PORT" OUTDATA_ACLR_B="CLEAR1" OUTDATA_REG_B="CLOCK1" WIDTH_A=64 WIDTH_B=8 WIDTH_BYTEENA_A=1 WIDTHAD_A=4 WIDTHAD_B=7 aclr1 address_a address_b addressstall_b clock0 clock1 clocken1 data_a q_b wren_a
//VERSION_BEGIN 17.1 cbx_altera_syncram_nd_impl 2017:10:19:05:46:40:SJ cbx_altsyncram 2017:10:19:05:46:40:SJ cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_lpm_add_sub 2017:10:19:05:46:40:SJ cbx_lpm_compare 2017:10:19:05:46:40:SJ cbx_lpm_decode 2017:10:19:05:46:40:SJ cbx_lpm_mux 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_nadder 2017:10:19:05:46:40:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ cbx_stratixiii 2017:10:19:05:46:40:SJ cbx_stratixv 2017:10:19:05:46:40:SJ cbx_util_mgl 2017:10:19:05:46:40:SJ  VERSION_END

//synthesis_resources = M10K 2 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  exp_3x3_ker_fifo_8_altsyncram
	( 
	aclr1,
	address_a,
	address_b,
	addressstall_b,
	clock0,
	clock1,
	clocken1,
	data_a,
	q_b,
	wren_a) /* synthesis synthesis_clearbox=1 */;
	input   aclr1;
	input   [3:0]  address_a;
	input   [6:0]  address_b;
	input   addressstall_b;
	input   clock0;
	input   clock1;
	input   clocken1;
	input   [63:0]  data_a;
	output   [7:0]  q_b;
	input   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr1;
	tri1   [6:0]  address_b;
	tri0   addressstall_b;
	tri1   clock0;
	tri1   clock1;
	tri1   clocken1;
	tri1   [63:0]  data_a;
	tri0   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block7a_0portbdataout;
	wire  [0:0]   wire_ram_block7a_1portbdataout;
	wire  [0:0]   wire_ram_block7a_2portbdataout;
	wire  [0:0]   wire_ram_block7a_3portbdataout;
	wire  [0:0]   wire_ram_block7a_4portbdataout;
	wire  [0:0]   wire_ram_block7a_5portbdataout;
	wire  [0:0]   wire_ram_block7a_6portbdataout;
	wire  [0:0]   wire_ram_block7a_7portbdataout;
	wire  [3:0]  address_a_wire;
	wire  [6:0]  address_b_wire;

	cyclonev_ram_block   ram_block7a_0
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.dftout(),
	.eccstatus(),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[3:0]}),
	.portadatain({data_a[56], data_a[48], data_a[40], data_a[32], data_a[24], data_a[16], data_a[8], data_a[0]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_0portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_0.clk0_core_clock_enable = "ena0",
		ram_block7a_0.clk0_input_clock_enable = "none",
		ram_block7a_0.clk1_core_clock_enable = "none",
		ram_block7a_0.clk1_input_clock_enable = "none",
		ram_block7a_0.clk1_output_clock_enable = "ena1",
		ram_block7a_0.connectivity_checking = "OFF",
		ram_block7a_0.data_interleave_offset_in_bits = 8,
		ram_block7a_0.data_interleave_width_in_bits = 1,
		ram_block7a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_0.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_0.operation_mode = "dual_port",
		ram_block7a_0.port_a_address_width = 4,
		ram_block7a_0.port_a_data_width = 8,
		ram_block7a_0.port_a_first_address = 0,
		ram_block7a_0.port_a_first_bit_number = 0,
		ram_block7a_0.port_a_last_address = 15,
		ram_block7a_0.port_a_logical_ram_depth = 16,
		ram_block7a_0.port_a_logical_ram_width = 64,
		ram_block7a_0.port_b_address_clear = "clear1",
		ram_block7a_0.port_b_address_clock = "clock1",
		ram_block7a_0.port_b_address_width = 7,
		ram_block7a_0.port_b_data_out_clear = "clear1",
		ram_block7a_0.port_b_data_out_clock = "clock1",
		ram_block7a_0.port_b_data_width = 1,
		ram_block7a_0.port_b_first_address = 0,
		ram_block7a_0.port_b_first_bit_number = 0,
		ram_block7a_0.port_b_last_address = 127,
		ram_block7a_0.port_b_logical_ram_depth = 128,
		ram_block7a_0.port_b_logical_ram_width = 8,
		ram_block7a_0.port_b_read_enable_clock = "clock1",
		ram_block7a_0.ram_block_type = "AUTO",
		ram_block7a_0.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block7a_1
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.dftout(),
	.eccstatus(),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[3:0]}),
	.portadatain({data_a[57], data_a[49], data_a[41], data_a[33], data_a[25], data_a[17], data_a[9], data_a[1]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_1portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_1.clk0_core_clock_enable = "ena0",
		ram_block7a_1.clk0_input_clock_enable = "none",
		ram_block7a_1.clk1_core_clock_enable = "none",
		ram_block7a_1.clk1_input_clock_enable = "none",
		ram_block7a_1.clk1_output_clock_enable = "ena1",
		ram_block7a_1.connectivity_checking = "OFF",
		ram_block7a_1.data_interleave_offset_in_bits = 8,
		ram_block7a_1.data_interleave_width_in_bits = 1,
		ram_block7a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_1.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_1.operation_mode = "dual_port",
		ram_block7a_1.port_a_address_width = 4,
		ram_block7a_1.port_a_data_width = 8,
		ram_block7a_1.port_a_first_address = 0,
		ram_block7a_1.port_a_first_bit_number = 1,
		ram_block7a_1.port_a_last_address = 15,
		ram_block7a_1.port_a_logical_ram_depth = 16,
		ram_block7a_1.port_a_logical_ram_width = 64,
		ram_block7a_1.port_b_address_clear = "clear1",
		ram_block7a_1.port_b_address_clock = "clock1",
		ram_block7a_1.port_b_address_width = 7,
		ram_block7a_1.port_b_data_out_clear = "clear1",
		ram_block7a_1.port_b_data_out_clock = "clock1",
		ram_block7a_1.port_b_data_width = 1,
		ram_block7a_1.port_b_first_address = 0,
		ram_block7a_1.port_b_first_bit_number = 1,
		ram_block7a_1.port_b_last_address = 127,
		ram_block7a_1.port_b_logical_ram_depth = 128,
		ram_block7a_1.port_b_logical_ram_width = 8,
		ram_block7a_1.port_b_read_enable_clock = "clock1",
		ram_block7a_1.ram_block_type = "AUTO",
		ram_block7a_1.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block7a_2
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.dftout(),
	.eccstatus(),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[3:0]}),
	.portadatain({data_a[58], data_a[50], data_a[42], data_a[34], data_a[26], data_a[18], data_a[10], data_a[2]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_2portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_2.clk0_core_clock_enable = "ena0",
		ram_block7a_2.clk0_input_clock_enable = "none",
		ram_block7a_2.clk1_core_clock_enable = "none",
		ram_block7a_2.clk1_input_clock_enable = "none",
		ram_block7a_2.clk1_output_clock_enable = "ena1",
		ram_block7a_2.connectivity_checking = "OFF",
		ram_block7a_2.data_interleave_offset_in_bits = 8,
		ram_block7a_2.data_interleave_width_in_bits = 1,
		ram_block7a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_2.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_2.operation_mode = "dual_port",
		ram_block7a_2.port_a_address_width = 4,
		ram_block7a_2.port_a_data_width = 8,
		ram_block7a_2.port_a_first_address = 0,
		ram_block7a_2.port_a_first_bit_number = 2,
		ram_block7a_2.port_a_last_address = 15,
		ram_block7a_2.port_a_logical_ram_depth = 16,
		ram_block7a_2.port_a_logical_ram_width = 64,
		ram_block7a_2.port_b_address_clear = "clear1",
		ram_block7a_2.port_b_address_clock = "clock1",
		ram_block7a_2.port_b_address_width = 7,
		ram_block7a_2.port_b_data_out_clear = "clear1",
		ram_block7a_2.port_b_data_out_clock = "clock1",
		ram_block7a_2.port_b_data_width = 1,
		ram_block7a_2.port_b_first_address = 0,
		ram_block7a_2.port_b_first_bit_number = 2,
		ram_block7a_2.port_b_last_address = 127,
		ram_block7a_2.port_b_logical_ram_depth = 128,
		ram_block7a_2.port_b_logical_ram_width = 8,
		ram_block7a_2.port_b_read_enable_clock = "clock1",
		ram_block7a_2.ram_block_type = "AUTO",
		ram_block7a_2.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block7a_3
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.dftout(),
	.eccstatus(),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[3:0]}),
	.portadatain({data_a[59], data_a[51], data_a[43], data_a[35], data_a[27], data_a[19], data_a[11], data_a[3]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_3portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_3.clk0_core_clock_enable = "ena0",
		ram_block7a_3.clk0_input_clock_enable = "none",
		ram_block7a_3.clk1_core_clock_enable = "none",
		ram_block7a_3.clk1_input_clock_enable = "none",
		ram_block7a_3.clk1_output_clock_enable = "ena1",
		ram_block7a_3.connectivity_checking = "OFF",
		ram_block7a_3.data_interleave_offset_in_bits = 8,
		ram_block7a_3.data_interleave_width_in_bits = 1,
		ram_block7a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_3.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_3.operation_mode = "dual_port",
		ram_block7a_3.port_a_address_width = 4,
		ram_block7a_3.port_a_data_width = 8,
		ram_block7a_3.port_a_first_address = 0,
		ram_block7a_3.port_a_first_bit_number = 3,
		ram_block7a_3.port_a_last_address = 15,
		ram_block7a_3.port_a_logical_ram_depth = 16,
		ram_block7a_3.port_a_logical_ram_width = 64,
		ram_block7a_3.port_b_address_clear = "clear1",
		ram_block7a_3.port_b_address_clock = "clock1",
		ram_block7a_3.port_b_address_width = 7,
		ram_block7a_3.port_b_data_out_clear = "clear1",
		ram_block7a_3.port_b_data_out_clock = "clock1",
		ram_block7a_3.port_b_data_width = 1,
		ram_block7a_3.port_b_first_address = 0,
		ram_block7a_3.port_b_first_bit_number = 3,
		ram_block7a_3.port_b_last_address = 127,
		ram_block7a_3.port_b_logical_ram_depth = 128,
		ram_block7a_3.port_b_logical_ram_width = 8,
		ram_block7a_3.port_b_read_enable_clock = "clock1",
		ram_block7a_3.ram_block_type = "AUTO",
		ram_block7a_3.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block7a_4
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.dftout(),
	.eccstatus(),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[3:0]}),
	.portadatain({data_a[60], data_a[52], data_a[44], data_a[36], data_a[28], data_a[20], data_a[12], data_a[4]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_4portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_4.clk0_core_clock_enable = "ena0",
		ram_block7a_4.clk0_input_clock_enable = "none",
		ram_block7a_4.clk1_core_clock_enable = "none",
		ram_block7a_4.clk1_input_clock_enable = "none",
		ram_block7a_4.clk1_output_clock_enable = "ena1",
		ram_block7a_4.connectivity_checking = "OFF",
		ram_block7a_4.data_interleave_offset_in_bits = 8,
		ram_block7a_4.data_interleave_width_in_bits = 1,
		ram_block7a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_4.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_4.operation_mode = "dual_port",
		ram_block7a_4.port_a_address_width = 4,
		ram_block7a_4.port_a_data_width = 8,
		ram_block7a_4.port_a_first_address = 0,
		ram_block7a_4.port_a_first_bit_number = 4,
		ram_block7a_4.port_a_last_address = 15,
		ram_block7a_4.port_a_logical_ram_depth = 16,
		ram_block7a_4.port_a_logical_ram_width = 64,
		ram_block7a_4.port_b_address_clear = "clear1",
		ram_block7a_4.port_b_address_clock = "clock1",
		ram_block7a_4.port_b_address_width = 7,
		ram_block7a_4.port_b_data_out_clear = "clear1",
		ram_block7a_4.port_b_data_out_clock = "clock1",
		ram_block7a_4.port_b_data_width = 1,
		ram_block7a_4.port_b_first_address = 0,
		ram_block7a_4.port_b_first_bit_number = 4,
		ram_block7a_4.port_b_last_address = 127,
		ram_block7a_4.port_b_logical_ram_depth = 128,
		ram_block7a_4.port_b_logical_ram_width = 8,
		ram_block7a_4.port_b_read_enable_clock = "clock1",
		ram_block7a_4.ram_block_type = "AUTO",
		ram_block7a_4.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block7a_5
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.dftout(),
	.eccstatus(),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[3:0]}),
	.portadatain({data_a[61], data_a[53], data_a[45], data_a[37], data_a[29], data_a[21], data_a[13], data_a[5]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_5portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_5.clk0_core_clock_enable = "ena0",
		ram_block7a_5.clk0_input_clock_enable = "none",
		ram_block7a_5.clk1_core_clock_enable = "none",
		ram_block7a_5.clk1_input_clock_enable = "none",
		ram_block7a_5.clk1_output_clock_enable = "ena1",
		ram_block7a_5.connectivity_checking = "OFF",
		ram_block7a_5.data_interleave_offset_in_bits = 8,
		ram_block7a_5.data_interleave_width_in_bits = 1,
		ram_block7a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_5.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_5.operation_mode = "dual_port",
		ram_block7a_5.port_a_address_width = 4,
		ram_block7a_5.port_a_data_width = 8,
		ram_block7a_5.port_a_first_address = 0,
		ram_block7a_5.port_a_first_bit_number = 5,
		ram_block7a_5.port_a_last_address = 15,
		ram_block7a_5.port_a_logical_ram_depth = 16,
		ram_block7a_5.port_a_logical_ram_width = 64,
		ram_block7a_5.port_b_address_clear = "clear1",
		ram_block7a_5.port_b_address_clock = "clock1",
		ram_block7a_5.port_b_address_width = 7,
		ram_block7a_5.port_b_data_out_clear = "clear1",
		ram_block7a_5.port_b_data_out_clock = "clock1",
		ram_block7a_5.port_b_data_width = 1,
		ram_block7a_5.port_b_first_address = 0,
		ram_block7a_5.port_b_first_bit_number = 5,
		ram_block7a_5.port_b_last_address = 127,
		ram_block7a_5.port_b_logical_ram_depth = 128,
		ram_block7a_5.port_b_logical_ram_width = 8,
		ram_block7a_5.port_b_read_enable_clock = "clock1",
		ram_block7a_5.ram_block_type = "AUTO",
		ram_block7a_5.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block7a_6
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.dftout(),
	.eccstatus(),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[3:0]}),
	.portadatain({data_a[62], data_a[54], data_a[46], data_a[38], data_a[30], data_a[22], data_a[14], data_a[6]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_6portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_6.clk0_core_clock_enable = "ena0",
		ram_block7a_6.clk0_input_clock_enable = "none",
		ram_block7a_6.clk1_core_clock_enable = "none",
		ram_block7a_6.clk1_input_clock_enable = "none",
		ram_block7a_6.clk1_output_clock_enable = "ena1",
		ram_block7a_6.connectivity_checking = "OFF",
		ram_block7a_6.data_interleave_offset_in_bits = 8,
		ram_block7a_6.data_interleave_width_in_bits = 1,
		ram_block7a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_6.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_6.operation_mode = "dual_port",
		ram_block7a_6.port_a_address_width = 4,
		ram_block7a_6.port_a_data_width = 8,
		ram_block7a_6.port_a_first_address = 0,
		ram_block7a_6.port_a_first_bit_number = 6,
		ram_block7a_6.port_a_last_address = 15,
		ram_block7a_6.port_a_logical_ram_depth = 16,
		ram_block7a_6.port_a_logical_ram_width = 64,
		ram_block7a_6.port_b_address_clear = "clear1",
		ram_block7a_6.port_b_address_clock = "clock1",
		ram_block7a_6.port_b_address_width = 7,
		ram_block7a_6.port_b_data_out_clear = "clear1",
		ram_block7a_6.port_b_data_out_clock = "clock1",
		ram_block7a_6.port_b_data_width = 1,
		ram_block7a_6.port_b_first_address = 0,
		ram_block7a_6.port_b_first_bit_number = 6,
		ram_block7a_6.port_b_last_address = 127,
		ram_block7a_6.port_b_logical_ram_depth = 128,
		ram_block7a_6.port_b_logical_ram_width = 8,
		ram_block7a_6.port_b_read_enable_clock = "clock1",
		ram_block7a_6.ram_block_type = "AUTO",
		ram_block7a_6.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block7a_7
	( 
	.clk0(clock0),
	.clk1(clock1),
	.clr1(aclr1),
	.dftout(),
	.eccstatus(),
	.ena0(wren_a),
	.ena1(clocken1),
	.portaaddr({address_a_wire[3:0]}),
	.portadatain({data_a[63], data_a[55], data_a[47], data_a[39], data_a[31], data_a[23], data_a[15], data_a[7]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_7portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_7.clk0_core_clock_enable = "ena0",
		ram_block7a_7.clk0_input_clock_enable = "none",
		ram_block7a_7.clk1_core_clock_enable = "none",
		ram_block7a_7.clk1_input_clock_enable = "none",
		ram_block7a_7.clk1_output_clock_enable = "ena1",
		ram_block7a_7.connectivity_checking = "OFF",
		ram_block7a_7.data_interleave_offset_in_bits = 8,
		ram_block7a_7.data_interleave_width_in_bits = 1,
		ram_block7a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_7.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_7.operation_mode = "dual_port",
		ram_block7a_7.port_a_address_width = 4,
		ram_block7a_7.port_a_data_width = 8,
		ram_block7a_7.port_a_first_address = 0,
		ram_block7a_7.port_a_first_bit_number = 7,
		ram_block7a_7.port_a_last_address = 15,
		ram_block7a_7.port_a_logical_ram_depth = 16,
		ram_block7a_7.port_a_logical_ram_width = 64,
		ram_block7a_7.port_b_address_clear = "clear1",
		ram_block7a_7.port_b_address_clock = "clock1",
		ram_block7a_7.port_b_address_width = 7,
		ram_block7a_7.port_b_data_out_clear = "clear1",
		ram_block7a_7.port_b_data_out_clock = "clock1",
		ram_block7a_7.port_b_data_width = 1,
		ram_block7a_7.port_b_first_address = 0,
		ram_block7a_7.port_b_first_bit_number = 7,
		ram_block7a_7.port_b_last_address = 127,
		ram_block7a_7.port_b_logical_ram_depth = 128,
		ram_block7a_7.port_b_logical_ram_width = 8,
		ram_block7a_7.port_b_read_enable_clock = "clock1",
		ram_block7a_7.ram_block_type = "AUTO",
		ram_block7a_7.lpm_type = "cyclonev_ram_block";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_b = {wire_ram_block7a_7portbdataout[0], wire_ram_block7a_6portbdataout[0], wire_ram_block7a_5portbdataout[0], wire_ram_block7a_4portbdataout[0], wire_ram_block7a_3portbdataout[0], wire_ram_block7a_2portbdataout[0], wire_ram_block7a_1portbdataout[0], wire_ram_block7a_0portbdataout[0]};
endmodule //exp_3x3_ker_fifo_8_altsyncram


//dffpipe DELAY=1 WIDTH=5 clock clrn d ALTERA_INTERNAL_OPTIONS=X_ON_VIOLATION_OPTION=OFF
//VERSION_BEGIN 17.1 cbx_a_gray2bin 2017:10:19:05:46:40:SJ cbx_a_graycounter 2017:10:19:05:46:40:SJ cbx_altdpram 2017:10:19:05:46:40:SJ cbx_altera_counter 2017:10:19:05:46:40:SJ cbx_altera_gray_counter 2017:10:19:05:46:40:SJ cbx_altera_syncram 2017:10:19:05:46:40:SJ cbx_altera_syncram_nd_impl 2017:10:19:05:46:40:SJ cbx_altsyncram 2017:10:19:05:46:40:SJ cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_dcfifo 2017:10:19:05:46:40:SJ cbx_fifo_common 2017:10:19:05:46:40:SJ cbx_lpm_add_sub 2017:10:19:05:46:40:SJ cbx_lpm_compare 2017:10:19:05:46:40:SJ cbx_lpm_counter 2017:10:19:05:46:40:SJ cbx_lpm_decode 2017:10:19:05:46:40:SJ cbx_lpm_mux 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_nadder 2017:10:19:05:46:40:SJ cbx_scfifo 2017:10:19:05:46:40:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ cbx_stratixiii 2017:10:19:05:46:40:SJ cbx_stratixv 2017:10:19:05:46:40:SJ cbx_util_mgl 2017:10:19:05:46:40:SJ  VERSION_END


//dffpipe DELAY=1 WIDTH=5 clock clrn d q ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 17.1 cbx_mgl 2017:10:19:06:38:12:SJ cbx_stratixii 2017:10:19:05:46:40:SJ cbx_util_mgl 2017:10:19:05:46:40:SJ  VERSION_END

//synthesis_resources = reg 5 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF"} *)
module  exp_3x3_ker_fifo_8_dffpipe
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [4:0]  d;
	output   [4:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[4:0]	dffe9a;
	wire ena;
	wire prn;
	wire sclr;

	// synopsys translate_off
	initial
		dffe9a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe9a <= {5{1'b1}};
		else if (clrn == 1'b0) dffe9a <= 5'b0;
		else if  (ena == 1'b1)   dffe9a <= (d & {5{(~ sclr)}});
	assign
		ena = 1'b1,
		prn = 1'b1,
		q = dffe9a,
		sclr = 1'b0;
endmodule //exp_3x3_ker_fifo_8_dffpipe

//synthesis_resources = reg 5 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"X_ON_VIOLATION_OPTION=OFF"} *)
module  exp_3x3_ker_fifo_8_alt_synch_pipe
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [4:0]  d;
	output   [4:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [4:0]   wire_dffpipe8_q;

	exp_3x3_ker_fifo_8_dffpipe   dffpipe8
	( 
	.clock(clock),
	.clrn(clrn),
	.d(d),
	.q(wire_dffpipe8_q));
	assign
		q = wire_dffpipe8_q;
endmodule //exp_3x3_ker_fifo_8_alt_synch_pipe


//dffpipe DELAY=1 WIDTH=5 clock clrn d q ALTERA_INTERNAL_OPTIONS=X_ON_VIOLATION_OPTION=OFF
//VERSION_BEGIN 17.1 cbx_a_gray2bin 2017:10:19:05:46:40:SJ cbx_a_graycounter 2017:10:19:05:46:40:SJ cbx_altdpram 2017:10:19:05:46:40:SJ cbx_altera_counter 2017:10:19:05:46:40:SJ cbx_altera_gray_counter 2017:10:19:05:46:40:SJ cbx_altera_syncram 2017:10:19:05:46:40:SJ cbx_altera_syncram_nd_impl 2017:10:19:05:46:40:SJ cbx_altsyncram 2017:10:19:05:46:40:SJ cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_dcfifo 2017:10:19:05:46:40:SJ cbx_fifo_common 2017:10:19:05:46:40:SJ cbx_lpm_add_sub 2017:10:19:05:46:40:SJ cbx_lpm_compare 2017:10:19:05:46:40:SJ cbx_lpm_counter 2017:10:19:05:46:40:SJ cbx_lpm_decode 2017:10:19:05:46:40:SJ cbx_lpm_mux 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_nadder 2017:10:19:05:46:40:SJ cbx_scfifo 2017:10:19:05:46:40:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ cbx_stratixiii 2017:10:19:05:46:40:SJ cbx_stratixv 2017:10:19:05:46:40:SJ cbx_util_mgl 2017:10:19:05:46:40:SJ  VERSION_END


//dffpipe DELAY=1 WIDTH=5 clock clrn d q ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 17.1 cbx_mgl 2017:10:19:06:38:12:SJ cbx_stratixii 2017:10:19:05:46:40:SJ cbx_util_mgl 2017:10:19:05:46:40:SJ  VERSION_END

//synthesis_resources = reg 5 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF"} *)
module  exp_3x3_ker_fifo_8_dffpipe1
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [4:0]  d;
	output   [4:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[4:0]	dffe11a;
	wire ena;
	wire prn;
	wire sclr;

	// synopsys translate_off
	initial
		dffe11a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe11a <= {5{1'b1}};
		else if (clrn == 1'b0) dffe11a <= 5'b0;
		else if  (ena == 1'b1)   dffe11a <= (d & {5{(~ sclr)}});
	assign
		ena = 1'b1,
		prn = 1'b1,
		q = dffe11a,
		sclr = 1'b0;
endmodule //exp_3x3_ker_fifo_8_dffpipe1

//synthesis_resources = reg 5 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"X_ON_VIOLATION_OPTION=OFF"} *)
module  exp_3x3_ker_fifo_8_alt_synch_pipe1
	( 
	clock,
	clrn,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   clrn;
	input   [4:0]  d;
	output   [4:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clrn;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [4:0]   wire_dffpipe10_q;

	exp_3x3_ker_fifo_8_dffpipe1   dffpipe10
	( 
	.clock(clock),
	.clrn(clrn),
	.d(d),
	.q(wire_dffpipe10_q));
	assign
		q = wire_dffpipe10_q;
endmodule //exp_3x3_ker_fifo_8_alt_synch_pipe1


//lpm_add_sub DEVICE_FAMILY="Cyclone V" LPM_DIRECTION="SUB" LPM_WIDTH=5 dataa datab result
//VERSION_BEGIN 17.1 cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_lpm_add_sub 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_nadder 2017:10:19:05:46:40:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ  VERSION_END


//lpm_compare DEVICE_FAMILY="Cyclone V" LPM_WIDTH=3 aeb dataa datab
//VERSION_BEGIN 17.1 cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_lpm_add_sub 2017:10:19:05:46:40:SJ cbx_lpm_compare 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_nadder 2017:10:19:05:46:40:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  exp_3x3_ker_fifo_8_cmpr
	( 
	aeb,
	dataa,
	datab) /* synthesis synthesis_clearbox=1 */;
	output   aeb;
	input   [2:0]  dataa;
	input   [2:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [2:0]  dataa;
	tri0   [2:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  aeb_result_wire;
	wire  [0:0]  aneb_result_wire;
	wire  [7:0]  data_wire;
	wire  eq_wire;

	assign
		aeb = eq_wire,
		aeb_result_wire = (~ aneb_result_wire),
		aneb_result_wire = (data_wire[0] | data_wire[1]),
		data_wire = {datab[2], dataa[2], datab[1], dataa[1], datab[0], dataa[0], (data_wire[6] ^ data_wire[7]), ((data_wire[2] ^ data_wire[3]) | (data_wire[4] ^ data_wire[5]))},
		eq_wire = aeb_result_wire;
endmodule //exp_3x3_ker_fifo_8_cmpr


//lpm_compare DEVICE_FAMILY="Cyclone V" LPM_WIDTH=2 aeb dataa datab
//VERSION_BEGIN 17.1 cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_lpm_add_sub 2017:10:19:05:46:40:SJ cbx_lpm_compare 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_nadder 2017:10:19:05:46:40:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  exp_3x3_ker_fifo_8_cmpr1
	( 
	aeb,
	dataa,
	datab) /* synthesis synthesis_clearbox=1 */;
	output   aeb;
	input   [1:0]  dataa;
	input   [1:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [1:0]  dataa;
	tri0   [1:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  aeb_result_wire;
	wire  [0:0]  aneb_result_wire;
	wire  [3:0]  data_wire;
	wire  eq_wire;

	assign
		aeb = eq_wire,
		aeb_result_wire = (~ aneb_result_wire),
		aneb_result_wire = ((data_wire[0] ^ data_wire[1]) | (data_wire[2] ^ data_wire[3])),
		data_wire = {datab[1], dataa[1], datab[0], dataa[0]},
		eq_wire = aeb_result_wire;
endmodule //exp_3x3_ker_fifo_8_cmpr1


//lpm_counter DEVICE_FAMILY="Cyclone V" lpm_avalue=1 lpm_direction="UP" lpm_port_updown="PORT_UNUSED" lpm_pvalue=1 lpm_width=3 aset clock cnt_en cout q
//VERSION_BEGIN 17.1 cbx_cycloneii 2017:10:19:05:46:40:SJ cbx_lpm_add_sub 2017:10:19:05:46:40:SJ cbx_lpm_compare 2017:10:19:05:46:40:SJ cbx_lpm_counter 2017:10:19:05:46:40:SJ cbx_lpm_decode 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ cbx_nadder 2017:10:19:05:46:40:SJ cbx_stratix 2017:10:19:05:46:40:SJ cbx_stratixii 2017:10:19:05:46:40:SJ  VERSION_END

//synthesis_resources = lut 3 reg 3 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"{-to counter_reg_bit[0]} POWER_UP_LEVEL=HIGH"} *)
module  exp_3x3_ker_fifo_8_cntr
	( 
	aset,
	clock,
	cnt_en,
	cout,
	q) /* synthesis synthesis_clearbox=1 */;
	input   aset;
	input   clock;
	input   cnt_en;
	output   cout;
	output   [2:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aset;
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	[2:0]	wire_counter_reg_bit_d;
	wire	[2:0]	wire_counter_reg_bit_asdata;
	reg	[2:0]	counter_reg_bit;
	wire	[2:0]	wire_counter_reg_bit_ena;
	wire	[2:0]	wire_counter_reg_bit_sload;
	wire  [0:0]   wire_counter_comb_bita_0cout;
	wire  [0:0]   wire_counter_comb_bita_1cout;
	wire  [0:0]   wire_counter_comb_bita_2cout;
	wire  [0:0]   wire_counter_comb_bita_0sumout;
	wire  [0:0]   wire_counter_comb_bita_1sumout;
	wire  [0:0]   wire_counter_comb_bita_2sumout;
	wire clk_en;
	wire  cout_actual;
	wire [2:0]  data;
	wire  external_cin;
	wire  lsb_cin;
	wire  [2:0]  s_val;
	wire  [2:0]  safe_q;
	wire sclr;
	wire sload;
	wire sset;
	wire  time_to_clear;
	wire  updown_dir;
	wire  updown_lsb;
	wire  updown_other_bits;

	// synopsys translate_off
	initial
		counter_reg_bit[0:0] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[0:0] <= {1{1'b1}};
		else if  (wire_counter_reg_bit_ena[0:0] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[0:0] <= 1'b0;
			else if (wire_counter_reg_bit_sload[0:0] == 1'b1) counter_reg_bit[0:0] <= wire_counter_reg_bit_asdata[0:0];
			else  counter_reg_bit[0:0] <= wire_counter_reg_bit_d[0:0];
	// synopsys translate_off
	initial
		counter_reg_bit[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[1:1] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[1:1] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[1:1] <= 1'b0;
			else if (wire_counter_reg_bit_sload[1:1] == 1'b1) counter_reg_bit[1:1] <= wire_counter_reg_bit_asdata[1:1];
			else  counter_reg_bit[1:1] <= wire_counter_reg_bit_d[1:1];
	// synopsys translate_off
	initial
		counter_reg_bit[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aset)
		if (aset == 1'b1) counter_reg_bit[2:2] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[2:2] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[2:2] <= 1'b0;
			else if (wire_counter_reg_bit_sload[2:2] == 1'b1) counter_reg_bit[2:2] <= wire_counter_reg_bit_asdata[2:2];
			else  counter_reg_bit[2:2] <= wire_counter_reg_bit_d[2:2];
	assign
		wire_counter_reg_bit_ena = {3{(clk_en & (((cnt_en | sclr) | sset) | sload))}},
		wire_counter_reg_bit_sload = {3{(sset | sload)}},
		wire_counter_reg_bit_asdata = (({3{sset}} & s_val) | ({3{(~ sset)}} & data)),
		wire_counter_reg_bit_d = {wire_counter_comb_bita_2sumout[0:0], wire_counter_comb_bita_1sumout[0:0], wire_counter_comb_bita_0sumout[0:0]};
	cyclonev_lcell_comb   counter_comb_bita_0
	( 
	.cin(lsb_cin),
	.combout(),
	.cout(wire_counter_comb_bita_0cout[0:0]),
	.datad(counter_reg_bit[0]),
	.dataf(updown_lsb),
	.shareout(),
	.sumout(wire_counter_comb_bita_0sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_0.extended_lut = "off",
		counter_comb_bita_0.lut_mask = 64'h000000000000FF00,
		counter_comb_bita_0.shared_arith = "off",
		counter_comb_bita_0.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_1
	( 
	.cin(wire_counter_comb_bita_0cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_1cout[0:0]),
	.datad(counter_reg_bit[1]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_1sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_1.extended_lut = "off",
		counter_comb_bita_1.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_1.shared_arith = "off",
		counter_comb_bita_1.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_2
	( 
	.cin(wire_counter_comb_bita_1cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_2cout[0:0]),
	.datad(counter_reg_bit[2]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_2sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_2.extended_lut = "off",
		counter_comb_bita_2.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_2.shared_arith = "off",
		counter_comb_bita_2.lpm_type = "cyclonev_lcell_comb";
	assign
		clk_en = 1'b1,
		cout = cout_actual,
		cout_actual = (((~ wire_counter_comb_bita_2cout[0:0]) ^ updown_other_bits) | (time_to_clear & updown_dir)),
		data = {3{1'b0}},
		external_cin = 1'b1,
		lsb_cin = 1'b0,
		q = safe_q,
		s_val = {3{1'b1}},
		safe_q = counter_reg_bit,
		sclr = 1'b0,
		sload = 1'b0,
		sset = 1'b0,
		time_to_clear = 1'b0,
		updown_dir = 1'b1,
		updown_lsb = updown_dir,
		updown_other_bits = ((~ external_cin) | updown_dir);
endmodule //exp_3x3_ker_fifo_8_cntr


//lpm_mux DEVICE_FAMILY="Cyclone V" LPM_SIZE=2 LPM_WIDTH=1 LPM_WIDTHS=1 data result sel
//VERSION_BEGIN 17.1 cbx_lpm_mux 2017:10:19:05:46:40:SJ cbx_mgl 2017:10:19:06:38:12:SJ  VERSION_END

//synthesis_resources = lut 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  exp_3x3_ker_fifo_8_mux
	( 
	data,
	result,
	sel) /* synthesis synthesis_clearbox=1 */;
	input   [1:0]  data;
	output   [0:0]  result;
	input   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [1:0]  data;
	tri0   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	wire_l1_w0_n0_mux_dataout;
	wire  [1:0]  data_wire;
	wire  [0:0]  result_wire_ext;
	wire  [0:0]  sel_wire;

	assign		wire_l1_w0_n0_mux_dataout = (sel_wire[0] === 1'b1) ? data_wire[1] : data_wire[0];
	assign
		data_wire = {data},
		result = result_wire_ext,
		result_wire_ext = {wire_l1_w0_n0_mux_dataout},
		sel_wire = {sel[0]};
endmodule //exp_3x3_ker_fifo_8_mux

//synthesis_resources = lut 13 M10K 2 reg 57 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF;REMOVE_DUPLICATE_REGISTERS=OFF;suppress_da_rule_internal=d101;suppress_da_rule_internal=d102;suppress_da_rule_internal=d103;SYNCHRONIZER_IDENTIFICATION=OFF;SYNCHRONIZATION_REGISTER_CHAIN_LENGTH = 1;-name CUT ON -from rdptr_g -to ws_dgrp|exp_3x3_ker_fifo_8_dffpipe1:dffpipe10|dffe11a;-name SDC_STATEMENT \"set_false_path -from *rdptr_g* -to *ws_dgrp|exp_3x3_ker_fifo_8_dffpipe1:dffpipe10|dffe11a* \""} *)
module  exp_3x3_ker_fifo_8_dcfifo
	( 
	aclr,
	data,
	q,
	rdclk,
	rdempty,
	rdreq,
	wrclk,
	wrreq,
	wrusedw) /* synthesis synthesis_clearbox=1 */;
	input   aclr;
	input   [63:0]  data;
	output   [7:0]  q;
	input   rdclk;
	output   rdempty;
	input   rdreq;
	input   wrclk;
	input   wrreq;
	output   [3:0]  wrusedw;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   aclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [4:0]   wire_wrptr_g_gray2bin_bin;
	wire  [4:0]   wire_ws_dgrp_gray2bin_bin;
	wire  [4:0]   wire_rdptr_g1p_q;
	wire  [4:0]   wire_wrptr_g1p_q;
	wire  [7:0]   wire_fifo_ram_q_b;
	reg	[4:0]	delayed_wrptr_g;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	rdemp_eq_comp_lsb_aeb;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	rdemp_eq_comp_msb_aeb;
	reg	[2:0]	rdptr_b;
	reg	[4:0]	rdptr_g;
	reg	wrfull_eq_comp_lsb_mux_reg;
	reg	wrfull_eq_comp_msb_mux_reg;
	(* ALTERA_ATTRIBUTE = {"suppress_da_rule_internal=S102"} *)
	reg	[4:0]	wrptr_g;
	wire  [4:0]   wire_rs_dgwp_q;
	wire  [4:0]   wire_ws_brp_q;
	wire  [4:0]   wire_ws_bwp_q;
	wire  [4:0]   wire_ws_dgrp_q;
	wire	[4:0]	wire_wrusedw_sub_dataa;
	wire	[4:0]	wire_wrusedw_sub_datab;
	wire	[4:0]	wire_wrusedw_sub_result;
	wire  wire_rdempty_eq_comp1_lsb_aeb;
	wire  wire_rdempty_eq_comp1_msb_aeb;
	wire  wire_rdempty_eq_comp_lsb_aeb;
	wire  wire_rdempty_eq_comp_msb_aeb;
	wire  wire_wrfull_eq_comp1_lsb_aeb;
	wire  wire_wrfull_eq_comp1_msb_aeb;
	wire  wire_wrfull_eq_comp_lsb_aeb;
	wire  wire_wrfull_eq_comp_msb_aeb;
	wire  wire_cntr_b_cout;
	wire  [2:0]   wire_cntr_b_q;
	wire  [0:0]   wire_rdemp_eq_comp_lsb_mux_result;
	wire  [0:0]   wire_rdemp_eq_comp_msb_mux_result;
	wire  [0:0]   wire_wrfull_eq_comp_lsb_mux_result;
	wire  [0:0]   wire_wrfull_eq_comp_msb_mux_result;
	wire  int_rdempty;
	wire  int_wrfull;
	wire  [3:0]  ram_address_a;
	wire  [6:0]  ram_address_b;
	wire  valid_rdreq;
	wire  valid_wrreq;
	wire  [4:0]  wrptr_g1s;
	wire  [4:0]  wrptr_gs;

	exp_3x3_ker_fifo_8_a_gray2bin   wrptr_g_gray2bin
	( 
	.bin(wire_wrptr_g_gray2bin_bin),
	.gray(wrptr_g));
	exp_3x3_ker_fifo_8_a_gray2bin   ws_dgrp_gray2bin
	( 
	.bin(wire_ws_dgrp_gray2bin_bin),
	.gray(wire_ws_dgrp_q));
	exp_3x3_ker_fifo_8_a_graycounter   rdptr_g1p
	( 
	.aclr(aclr),
	.clock(rdclk),
	.cnt_en((valid_rdreq & wire_cntr_b_cout)),
	.q(wire_rdptr_g1p_q));
	exp_3x3_ker_fifo_8_a_graycounter1   wrptr_g1p
	( 
	.aclr(aclr),
	.clock(wrclk),
	.cnt_en(valid_wrreq),
	.q(wire_wrptr_g1p_q));
	exp_3x3_ker_fifo_8_altsyncram   fifo_ram
	( 
	.aclr1(aclr),
	.address_a(ram_address_a),
	.address_b(ram_address_b),
	.addressstall_b((~ valid_rdreq)),
	.clock0(wrclk),
	.clock1(rdclk),
	.clocken1(valid_rdreq),
	.data_a(data),
	.q_b(wire_fifo_ram_q_b),
	.wren_a(valid_wrreq));
	// synopsys translate_off
	initial
		delayed_wrptr_g = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  posedge aclr)
		if (aclr == 1'b1) delayed_wrptr_g <= 5'b0;
		else  delayed_wrptr_g <= wrptr_g;
	// synopsys translate_off
	initial
		rdemp_eq_comp_lsb_aeb = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdemp_eq_comp_lsb_aeb <= {1{1'b1}};
		else  rdemp_eq_comp_lsb_aeb <= wire_rdemp_eq_comp_lsb_mux_result;
	// synopsys translate_off
	initial
		rdemp_eq_comp_msb_aeb = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdemp_eq_comp_msb_aeb <= {1{1'b1}};
		else  rdemp_eq_comp_msb_aeb <= wire_rdemp_eq_comp_msb_mux_result;
	// synopsys translate_off
	initial
		rdptr_b = 0;
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdptr_b <= 3'b0;
		else if  (valid_rdreq == 1'b1)   rdptr_b <= wire_cntr_b_q;
	// synopsys translate_off
	initial
		rdptr_g = 0;
	// synopsys translate_on
	always @ ( posedge rdclk or  posedge aclr)
		if (aclr == 1'b1) rdptr_g <= 5'b0;
		else if  (valid_rdreq == 1'b1)   rdptr_g <= wire_rdptr_g1p_q;
	// synopsys translate_off
	initial
		wrfull_eq_comp_lsb_mux_reg = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  posedge aclr)
		if (aclr == 1'b1) wrfull_eq_comp_lsb_mux_reg <= 1'b0;
		else  wrfull_eq_comp_lsb_mux_reg <= wire_wrfull_eq_comp_lsb_mux_result;
	// synopsys translate_off
	initial
		wrfull_eq_comp_msb_mux_reg = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  posedge aclr)
		if (aclr == 1'b1) wrfull_eq_comp_msb_mux_reg <= 1'b0;
		else  wrfull_eq_comp_msb_mux_reg <= wire_wrfull_eq_comp_msb_mux_result;
	// synopsys translate_off
	initial
		wrptr_g = 0;
	// synopsys translate_on
	always @ ( posedge wrclk or  posedge aclr)
		if (aclr == 1'b1) wrptr_g <= 5'b0;
		else if  (valid_wrreq == 1'b1)   wrptr_g <= wire_wrptr_g1p_q;
	exp_3x3_ker_fifo_8_alt_synch_pipe   rs_dgwp
	( 
	.clock(rdclk),
	.clrn((~ aclr)),
	.d(delayed_wrptr_g),
	.q(wire_rs_dgwp_q));
	exp_3x3_ker_fifo_8_dffpipe   ws_brp
	( 
	.clock(wrclk),
	.clrn((~ aclr)),
	.d(wire_ws_dgrp_gray2bin_bin),
	.q(wire_ws_brp_q));
	exp_3x3_ker_fifo_8_dffpipe   ws_bwp
	( 
	.clock(wrclk),
	.clrn((~ aclr)),
	.d(wire_wrptr_g_gray2bin_bin),
	.q(wire_ws_bwp_q));
	exp_3x3_ker_fifo_8_alt_synch_pipe1   ws_dgrp
	( 
	.clock(wrclk),
	.clrn((~ aclr)),
	.d(rdptr_g),
	.q(wire_ws_dgrp_q));
	assign
		wire_wrusedw_sub_result = wire_wrusedw_sub_dataa - wire_wrusedw_sub_datab;
	assign
		wire_wrusedw_sub_dataa = wire_ws_bwp_q,
		wire_wrusedw_sub_datab = wire_ws_brp_q;
	exp_3x3_ker_fifo_8_cmpr   rdempty_eq_comp1_lsb
	( 
	.aeb(wire_rdempty_eq_comp1_lsb_aeb),
	.dataa(delayed_wrptr_g[2:0]),
	.datab(wire_rdptr_g1p_q[2:0]));
	exp_3x3_ker_fifo_8_cmpr1   rdempty_eq_comp1_msb
	( 
	.aeb(wire_rdempty_eq_comp1_msb_aeb),
	.dataa(delayed_wrptr_g[4:3]),
	.datab(wire_rdptr_g1p_q[4:3]));
	exp_3x3_ker_fifo_8_cmpr   rdempty_eq_comp_lsb
	( 
	.aeb(wire_rdempty_eq_comp_lsb_aeb),
	.dataa(delayed_wrptr_g[2:0]),
	.datab(rdptr_g[2:0]));
	exp_3x3_ker_fifo_8_cmpr1   rdempty_eq_comp_msb
	( 
	.aeb(wire_rdempty_eq_comp_msb_aeb),
	.dataa(delayed_wrptr_g[4:3]),
	.datab(rdptr_g[4:3]));
	exp_3x3_ker_fifo_8_cmpr   wrfull_eq_comp1_lsb
	( 
	.aeb(wire_wrfull_eq_comp1_lsb_aeb),
	.dataa(rdptr_g[2:0]),
	.datab(wrptr_g1s[2:0]));
	exp_3x3_ker_fifo_8_cmpr1   wrfull_eq_comp1_msb
	( 
	.aeb(wire_wrfull_eq_comp1_msb_aeb),
	.dataa(rdptr_g[4:3]),
	.datab(wrptr_g1s[4:3]));
	exp_3x3_ker_fifo_8_cmpr   wrfull_eq_comp_lsb
	( 
	.aeb(wire_wrfull_eq_comp_lsb_aeb),
	.dataa(rdptr_g[2:0]),
	.datab(wrptr_gs[2:0]));
	exp_3x3_ker_fifo_8_cmpr1   wrfull_eq_comp_msb
	( 
	.aeb(wire_wrfull_eq_comp_msb_aeb),
	.dataa(rdptr_g[4:3]),
	.datab(wrptr_gs[4:3]));
	exp_3x3_ker_fifo_8_cntr   cntr_b
	( 
	.aset(aclr),
	.clock(rdclk),
	.cnt_en(valid_rdreq),
	.cout(wire_cntr_b_cout),
	.q(wire_cntr_b_q));
	exp_3x3_ker_fifo_8_mux   rdemp_eq_comp_lsb_mux
	( 
	.data({wire_rdempty_eq_comp1_lsb_aeb, wire_rdempty_eq_comp_lsb_aeb}),
	.result(wire_rdemp_eq_comp_lsb_mux_result),
	.sel(valid_rdreq));
	exp_3x3_ker_fifo_8_mux   rdemp_eq_comp_msb_mux
	( 
	.data({wire_rdempty_eq_comp1_msb_aeb, wire_rdempty_eq_comp_msb_aeb}),
	.result(wire_rdemp_eq_comp_msb_mux_result),
	.sel(valid_rdreq));
	exp_3x3_ker_fifo_8_mux   wrfull_eq_comp_lsb_mux
	( 
	.data({wire_wrfull_eq_comp1_lsb_aeb, wire_wrfull_eq_comp_lsb_aeb}),
	.result(wire_wrfull_eq_comp_lsb_mux_result),
	.sel(valid_wrreq));
	exp_3x3_ker_fifo_8_mux   wrfull_eq_comp_msb_mux
	( 
	.data({wire_wrfull_eq_comp1_msb_aeb, wire_wrfull_eq_comp_msb_aeb}),
	.result(wire_wrfull_eq_comp_msb_mux_result),
	.sel(valid_wrreq));
	assign
		int_rdempty = (rdemp_eq_comp_lsb_aeb & rdemp_eq_comp_msb_aeb),
		int_wrfull = (wrfull_eq_comp_lsb_mux_reg & wrfull_eq_comp_msb_mux_reg),
		q = wire_fifo_ram_q_b,
		ram_address_a = {(wrptr_g[4] ^ wrptr_g[3]), wrptr_g[2:0]},
		ram_address_b = {(wire_rdptr_g1p_q[4] ^ wire_rdptr_g1p_q[3]), wire_rdptr_g1p_q[2:0], wire_cntr_b_q},
		rdempty = int_rdempty,
		valid_rdreq = (rdreq & (~ int_rdempty)),
		valid_wrreq = (wrreq & (~ int_wrfull)),
		wrptr_g1s = {(~ wire_wrptr_g1p_q[4]), (~ wire_wrptr_g1p_q[3]), wire_wrptr_g1p_q[2:0]},
		wrptr_gs = {(~ wrptr_g[4]), (~ wrptr_g[3]), wrptr_g[2:0]},
		wrusedw = {wire_wrusedw_sub_result[3:0]};
endmodule //exp_3x3_ker_fifo_8_dcfifo
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module exp_3x3_ker_fifo_8 (
	aclr,
	data,
	rdclk,
	rdreq,
	wrclk,
	wrreq,
	q,
	rdempty,
	wrusedw)/* synthesis synthesis_clearbox = 1 */;

	input	  aclr;
	input	[63:0]  data;
	input	  rdclk;
	input	  rdreq;
	input	  wrclk;
	input	  wrreq;
	output	[7:0]  q;
	output	  rdempty;
	output	[3:0]  wrusedw;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0	  aclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [7:0] sub_wire0;
	wire  sub_wire1;
	wire [3:0] sub_wire2;
	wire [7:0] q = sub_wire0[7:0];
	wire  rdempty = sub_wire1;
	wire [3:0] wrusedw = sub_wire2[3:0];

	exp_3x3_ker_fifo_8_dcfifo	exp_3x3_ker_fifo_8_dcfifo_component (
				.aclr (aclr),
				.data (data),
				.rdclk (rdclk),
				.rdreq (rdreq),
				.wrclk (wrclk),
				.wrreq (wrreq),
				.q (sub_wire0),
				.rdempty (sub_wire1),
				.wrusedw (sub_wire2));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: AlmostEmpty NUMERIC "0"
// Retrieval info: PRIVATE: AlmostEmptyThr NUMERIC "-1"
// Retrieval info: PRIVATE: AlmostFull NUMERIC "0"
// Retrieval info: PRIVATE: AlmostFullThr NUMERIC "-1"
// Retrieval info: PRIVATE: CLOCKS_ARE_SYNCHRONIZED NUMERIC "1"
// Retrieval info: PRIVATE: Clock NUMERIC "4"
// Retrieval info: PRIVATE: Depth NUMERIC "16"
// Retrieval info: PRIVATE: Empty NUMERIC "1"
// Retrieval info: PRIVATE: Full NUMERIC "1"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: PRIVATE: LE_BasedFIFO NUMERIC "0"
// Retrieval info: PRIVATE: LegacyRREQ NUMERIC "1"
// Retrieval info: PRIVATE: MAX_DEPTH_BY_9 NUMERIC "0"
// Retrieval info: PRIVATE: OVERFLOW_CHECKING NUMERIC "0"
// Retrieval info: PRIVATE: Optimize NUMERIC "2"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: UNDERFLOW_CHECKING NUMERIC "0"
// Retrieval info: PRIVATE: UsedW NUMERIC "1"
// Retrieval info: PRIVATE: Width NUMERIC "64"
// Retrieval info: PRIVATE: dc_aclr NUMERIC "1"
// Retrieval info: PRIVATE: diff_widths NUMERIC "1"
// Retrieval info: PRIVATE: msb_usedw NUMERIC "0"
// Retrieval info: PRIVATE: output_width NUMERIC "8"
// Retrieval info: PRIVATE: rsEmpty NUMERIC "1"
// Retrieval info: PRIVATE: rsFull NUMERIC "0"
// Retrieval info: PRIVATE: rsUsedW NUMERIC "0"
// Retrieval info: PRIVATE: sc_aclr NUMERIC "0"
// Retrieval info: PRIVATE: sc_sclr NUMERIC "0"
// Retrieval info: PRIVATE: wsEmpty NUMERIC "0"
// Retrieval info: PRIVATE: wsFull NUMERIC "0"
// Retrieval info: PRIVATE: wsUsedW NUMERIC "1"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: CONSTANT: LPM_NUMWORDS NUMERIC "16"
// Retrieval info: CONSTANT: LPM_SHOWAHEAD STRING "OFF"
// Retrieval info: CONSTANT: LPM_TYPE STRING "dcfifo_mixed_widths"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "64"
// Retrieval info: CONSTANT: LPM_WIDTHU NUMERIC "4"
// Retrieval info: CONSTANT: LPM_WIDTHU_R NUMERIC "7"
// Retrieval info: CONSTANT: LPM_WIDTH_R NUMERIC "8"
// Retrieval info: CONSTANT: OVERFLOW_CHECKING STRING "ON"
// Retrieval info: CONSTANT: RDSYNC_DELAYPIPE NUMERIC "3"
// Retrieval info: CONSTANT: READ_ACLR_SYNCH STRING "OFF"
// Retrieval info: CONSTANT: UNDERFLOW_CHECKING STRING "ON"
// Retrieval info: CONSTANT: USE_EAB STRING "ON"
// Retrieval info: CONSTANT: WRITE_ACLR_SYNCH STRING "OFF"
// Retrieval info: CONSTANT: WRSYNC_DELAYPIPE NUMERIC "3"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT GND "aclr"
// Retrieval info: USED_PORT: data 0 0 64 0 INPUT NODEFVAL "data[63..0]"
// Retrieval info: USED_PORT: q 0 0 8 0 OUTPUT NODEFVAL "q[7..0]"
// Retrieval info: USED_PORT: rdclk 0 0 0 0 INPUT NODEFVAL "rdclk"
// Retrieval info: USED_PORT: rdempty 0 0 0 0 OUTPUT NODEFVAL "rdempty"
// Retrieval info: USED_PORT: rdreq 0 0 0 0 INPUT NODEFVAL "rdreq"
// Retrieval info: USED_PORT: wrclk 0 0 0 0 INPUT NODEFVAL "wrclk"
// Retrieval info: USED_PORT: wrreq 0 0 0 0 INPUT NODEFVAL "wrreq"
// Retrieval info: USED_PORT: wrusedw 0 0 4 0 OUTPUT NODEFVAL "wrusedw[3..0]"
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: CONNECT: @data 0 0 64 0 data 0 0 64 0
// Retrieval info: CONNECT: @rdclk 0 0 0 0 rdclk 0 0 0 0
// Retrieval info: CONNECT: @rdreq 0 0 0 0 rdreq 0 0 0 0
// Retrieval info: CONNECT: @wrclk 0 0 0 0 wrclk 0 0 0 0
// Retrieval info: CONNECT: @wrreq 0 0 0 0 wrreq 0 0 0 0
// Retrieval info: CONNECT: q 0 0 8 0 @q 0 0 8 0
// Retrieval info: CONNECT: rdempty 0 0 0 0 @rdempty 0 0 0 0
// Retrieval info: CONNECT: wrusedw 0 0 4 0 @wrusedw 0 0 4 0
// Retrieval info: GEN_FILE: TYPE_NORMAL exp_3x3_ker_fifo_8.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL exp_3x3_ker_fifo_8.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL exp_3x3_ker_fifo_8.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL exp_3x3_ker_fifo_8.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL exp_3x3_ker_fifo_8_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL exp_3x3_ker_fifo_8_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL exp_3x3_ker_fifo_8_syn.v TRUE
